### ISSUE TITLE
Failure to logout

### ISSUE THREAD

**Issue by patricknee** [stormpath/stormpath-sdk-angular#22]
The sample project available at https://github.com/stormpath/stormpath-angular2-express-example.git works fine. Restructuring the app to something more realistic introduces a few problems. Restructured project is available at the following repository, with read me explaining the changes (in short: routing, three components routing, dedicated login page).

https://github.com/patricknee/stormpath-angular2-testbed

Logout link fails to consistently log out. I would estimate logout probability at 40% on the first try. Repeatedly hitting the logout link will eventually cause logout.

**Comment by mraible** [comment]
@patricknee Thanks for taking the time to create a new, restructured project and reporting the issues you found after making these changes! I'll work on fixing these before the end of the year.
