### ISSUE TITLE
Forgot password? redirects to Home

### ISSUE THREAD

**Issue by patricknee** [stormpath/stormpath-sdk-angular#24]
The sample project available at https://github.com/stormpath/stormpath-angular2-express-example.git works fine. Restructuring the app to something more realistic introduces a few problems. Restructured project is available at the following repository, with read me explaining the changes (in short: routing, three components routing, dedicated login page).

https://github.com/patricknee/stormpath-angular2-testbed

Click "Login" then "Forgot password?" and user is redirected to Home page.

**Comment by mraible** [comment]
Changing the forgot password link to the following seems to fix the problem:

```html
<a href="#" (click)="forgot(); false">&nbsp;Forgot Password?</a>
```
