### ISSUE TITLE
Enable link on SPA

### ISSUE THREAD

**Issue by patricknee** [stormpath/stormpath-sdk-angular#25]
The sample project available at https://github.com/stormpath/stormpath-angular2-express-example.git works fine. Restructuring the app to something more realistic introduces a few problems. Restructured project is available at the following repository, with read me explaining the changes (in short: routing, three components routing, dedicated login page).

https://github.com/patricknee/stormpath-angular2-testbed

In a signal page application, what is the best way to enable/disable a feature/link based on user's role assignments?

Specifically, in this application on the Dashboard page, what is the correct way to enable/disable the shown links?

At log in, what is the best way to expand the user's roles (which appears to be the Stormpath mechanism for getting roles) without making a separate call and then storing the values in my own code?

**Comment by mraible** [comment]
@patricknee Can you please look at https://github.com/stormpath/stormpath-sdk-angular/pull/41 and see if these directives might work for you? You should be able to checkout the branch and run `npm start` to test.

**Comment by mraible** [comment]
Closing because of lack of response.
