### ISSUE TITLE
User ID

### ISSUE THREAD

**Issue by patricknee** [stormpath/stormpath-sdk-angular#26]
I need to assign the user a unique ID (for tying the user to custom database information); it should survive email changes.

It appears Stormpath assigns users an ID. However, this ID doesn't seem to be available in the user's JSON data (https://docs.stormpath.com/nodejs/express/latest/user_data.html#current-user-json-api). 

If there isn't a way to elegantly call user.id, why not? It doesn't appear to be a hidden value since I could parse the account.href and get the value...

**Comment by rdegges** [comment]
We're going to be exposing the `id` field via our core API service eventually -- just haven't gotten around to it yet. For now, the best thing to do is parse the HREF to get the ID -- we will never change it.
