### ISSUE TITLE
Type 'Observable<boolean | Account>' is not assignable to type 'Observable<boolean | Account>'.

### ISSUE THREAD

**Issue by consigliory** [stormpath/stormpath-sdk-angular#55]
(23,9): error TS90010: Type 'Observable<boolean | Account>' is not assignable to type 'Observable<boolean | Account>'. Two different types with this name exis
t, but they are unrelated.
        Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'

**Comment by mraible** [comment]
I've seen this when trying to use `npm link`, but not when installing it using `npm install angular-stormpath --save`. 

If you want to use `npm link` to use this module in another Angular project, follow the steps below:

1. Build this project using `npm run build:dist`.
2. Run `npm link` in this project's directory.
3. Run `npm link angular-stormpath` in the `<test-project>`.
4. Run `rm -rf node_modules/angular-stormpath/node_modules` in `<test-project>`.
5. Manually install dependencies required by `angular-stormpath`:

```
npm install ng2-webstorage angular2-cookie --save
```

**Comment by consigliory** [comment]
I used http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/
then installed angular-stormpath and for some reason it does not work out of the box

**Comment by consigliory** [comment]
you are extreemly quick!

**Comment by consigliory** [comment]
I used npm install angular-stormpath --save

**Comment by consigliory** [comment]
An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: Error: Unexpected value 'StormpathModule' imported by the module 'AppModule'
at /Users/roman_petrenko/git/source/Kuda/ClientApp/dist/vendor.js:27993:38
at Array.forEach (native)
at CompileMetadataResolver.getNgModuleMetadata (/Users/roman_petrenko/git/source/Kuda/ClientApp/dist/vendor.js:27978:47)
at RuntimeCompiler._compileComponents (/Users/roman_petrenko/git/source/Kuda/ClientApp/dist/vendor.js:30699:50)
at RuntimeCompiler._compileModuleAndComponents (/Users/roman_petrenko/git/source/Kuda/ClientApp/dist/vendor.js:30637:40)
at RuntimeCompiler.compileModuleAsync (/Users/roman_petrenko/git/source/Kuda/ClientApp/dist/vendor.js:30628:24)
at NodePlatform.bootstrapModule (/Users/roman_petrenko/git/source/Kuda/ClientApp/dist/vendor.js:131264:26)
at NodePlatform.serializeModule (/Users/roman_petrenko/git/source/Kuda/ClientApp/dist/vendor.js:130936:23)
at /Users/roman_petrenko/git/source/Kuda/ClientApp/dist/main-server.js:74:63
at ZoneDelegate.invoke (/Users/roman_petrenko/git/source/Kuda/ClientApp/dist/vendor.js:49622:27)
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()

**Comment by mraible** [comment]
Is it possible for you to upload your project to a GitHub repo?

**Comment by consigliory** [comment]
using gitlab. give me a min to import it to githab

**Comment by consigliory** [comment]
https://github.com/consigliory/kuda

**Comment by mraible** [comment]
Is it possible run this app from the command line? When I try `dotnet run` on my Mac, I get the following error:

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Call to Node module failed with error: Prerendering failed because of error: Error: Cannot find module '/Users/mraible/dev/kuda/ClientApp/dist/main-server'
          at Function.Module._resolveFilename (module.js:469:15)
          at Function.Module._load (module.js:417:25)
          at Module.require (module.js:497:17)
          at require (internal/module.js:20:19)
          at findBootModule (/private/var/folders/_g/h5m4s5_50175ntlmwkf0hw9h0000gn/T/tmp432QTX.tmp:111:17)
          at findRenderToStringFunc (/private/var/folders/_g/h5m4s5_50175ntlmwkf0hw9h0000gn/T/tmp432QTX.tmp:116:28)
          at renderToStringImpl (/private/var/folders/_g/h5m4s5_50175ntlmwkf0hw9h0000gn/T/tmp432QTX.tmp:75:51)
          at /private/var/folders/_g/h5m4s5_50175ntlmwkf0hw9h0000gn/T/tmpMktFZF.tmp:113:19
          at IncomingMessage.<anonymous> (/private/var/folders/_g/h5m4s5_50175ntlmwkf0hw9h0000gn/T/tmpMktFZF.tmp:132:38)
          at emitNone (events.js:86:13)
      Current directory is: /Users/mraible/dev/kuda
```

**Comment by consigliory** [comment]
)) it should be but currently I have same issue as you.

**Comment by consigliory** [comment]
any ideas?

**Comment by mraible** [comment]
Try adding `angular-stormpath` to `webpack.config.vendor.js` and running `webpack --config webpack.config.vendor.js`. I tried this and I get a new error: `TypeError: Cannot read property 'SelectorMatcher' of undefined`. This seems to be caused by [a bug in Angular Universal](https://github.com/angular/universal/pull/607).

**Comment by mraible** [comment]
FWIW, I used the Angular 2 Yeoman Generator to create my project.

http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/

This template seems quite out-of-date since it uses Angular 2.0.2. Your project seems to use a similar template.

**Comment by consigliory** [comment]
not sure what you mean. is there any newer which supports angular universal?

**Comment by mraible** [comment]
I'm not sure. I'm not able to get past the issue you found.

`Unexpected value 'StormpathModule' imported by the module 'AppModule'`

I believe this is due to the webpack configuration, but I'm not sure.

**Comment by consigliory** [comment]
just tried use it in https://github.com/MarkPieszak/aspnetcore-angular2-universal and same issue.

**Comment by consigliory** [comment]
I did upgraded to latest angular 2.4.5 and works fine. but still need to make your module work. Can you suggest how fix issue with webpack?

**Comment by mraible** [comment]
Are you trying to use the previously mentioned `aspnetcore-angular2-universal`? If so, it looks like it's using Angular 2.4.5 and Webpack 2.2.0. I'm not sure at this point, maybe we need to make changes so it works with angular2-universal?

**Comment by consigliory** [comment]
Hi. I got response from Steve Senderson. Here is his suggestion https://github.com/aspnet/JavaScriptServices/issues/623

**Comment by consigliory** [comment]
We really need serverside render and it looks like there is no reason why it should not be possible to use stormpath module in aspnetcore-angular2-universal. But it still not work out of the box. Maybe there is some minor config should be tuned to make it possible.
