### ISSUE TITLE
Logout doesn't seem to clear tokenstore when CookieTokenStoreManager

### ISSUE THREAD

**Issue by tdonovancsra** [stormpath/stormpath-sdk-angular#69]
The fix in 0.1.2 doesn't seem to work as expected

The null guard just keeps the error away but it doesn’t get rid of the cookie.
 
The way to reproduce.  **Don’t use incognito**
 
1.	Register a brand new user.
2.	Verify
3.	Log in
4.	Kill browser
5.	Open browser got to localhost:4200
6.	Still picks up cookie.
7.	Call logout – The guard protects error but doesn’t remove token
8.	Close browser
9.	Open browser still picks up cookie.

**Comment by mraible** [comment]
This won't happen with a default `Http` service that doesn't share cookies cross-domain. Closing this ticket since it's not really an Angular SDK issue. Please follow https://github.com/stormpath/stormpath-sdk-java/issues/1304 for a resolution.
